# Generated by Django 3.2.25 on 2024-07-24 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='user_address',
            new_name='address',
        ),
    ]
