# Generated by Django 3.2.25 on 2024-07-29 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOTP',
        ),
    ]
